-- Table: public.Factories

-- DROP TABLE IF EXISTS public."Factories";

CREATE TABLE IF NOT EXISTS public."Factories"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FactoryId" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "FactoryName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Factories" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

-- Table: public.Projects

-- DROP TABLE IF EXISTS public."Projects";

CREATE TABLE IF NOT EXISTS public."Projects"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ProjectId" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "ProjectName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "FactoryId" integer NOT NULL,
    "Role" text COLLATE pg_catalog."default",
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

-- Table: public.Groups

-- DROP TABLE IF EXISTS public."Groups";

CREATE TABLE IF NOT EXISTS public."Groups"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "GroupName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "ProjectId" integer NOT NULL,
    "Description" character varying(255) COLLATE pg_catalog."default",
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Groups" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;


-- Table: public.Products

-- DROP TABLE IF EXISTS public."Products";

CREATE TABLE IF NOT EXISTS public."Products"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Price" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;


-- Table: public.Roles

-- DROP TABLE IF EXISTS public."Roles";

CREATE TABLE IF NOT EXISTS public."Roles"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "RoleId" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "RoleName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Description" character varying(255) COLLATE pg_catalog."default",
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

-- Table: public.Accounts

-- DROP TABLE IF EXISTS public."Accounts";

CREATE TABLE IF NOT EXISTS public."Accounts"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "AccountId" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "AccountPassword" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "OsType" integer NOT NULL,
    "ProjectId" integer NOT NULL,
    "ServerIp" character varying(45) COLLATE pg_catalog."default",
    "Port" integer,
    "Description" character varying(500) COLLATE pg_catalog."default",
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Accounts_Projects_ProjectId" FOREIGN KEY ("ProjectId")
        REFERENCES public."Projects" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

-- Index: IX_Accounts_ProjectId

-- DROP INDEX IF EXISTS public."IX_Accounts_ProjectId";

CREATE INDEX IF NOT EXISTS "IX_Accounts_ProjectId"
    ON public."Accounts" USING btree
    ("ProjectId" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

-- Table: public.Users

-- DROP TABLE IF EXISTS public."Users";

CREATE TABLE IF NOT EXISTS public."Users"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "UserName" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Password" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "FactoryId" integer,
    "Email" character varying(100) COLLATE pg_catalog."default",
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Factories_FactoryId" FOREIGN KEY ("FactoryId")
        REFERENCES public."Factories" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

-- Index: IX_Users_FactoryId

-- DROP INDEX IF EXISTS public."IX_Users_FactoryId";

CREATE INDEX IF NOT EXISTS "IX_Users_FactoryId"
    ON public."Users" USING btree
    ("FactoryId" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
